In [1]:
import numpy as np


In [2]:
#check Version

print(np.__version__)

2.3.2


In [4]:
#1D Array
import numpy as np

arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [5]:
#2D Array
arr = np.array ([
    [1,2,3],
    [4,5,6]
])

print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
#3D Array
arr = np.array([
    [
        [1,2],
        [3,4]
    ],

    [
        [5,6],
        [7,8]
    ]
])

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
print(type(arr))

<class 'numpy.ndarray'>


3. Array Properties

In [9]:
arr =np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


In [10]:
print (arr.shape)

(2, 3)


In [11]:
print(arr.size)

6


In [12]:
print(arr.dtype)

int64


4. Creating Special Arrays

In [13]:
#Zeros
print(np.zeros((5,6)))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [14]:
#Ones
print(np.ones((2,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
#Identify Matrix
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
#Full
print(np.full((3,3),100))

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [17]:
#Random Integer
print(np.random.randint(1,100,(4,4)))

[[46 68 28 58]
 [45 17 28 14]
 [42 71 15 34]
 [63 86 41 44]]


5. Sequence Array

In [18]:
print(np.arange(1,20))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [19]:
print(np.arange(0,20,3))

[ 0  3  6  9 12 15 18]


6. Reshape

In [ ]:
import numpy as np

arr=np.arange(12)
print(arr.reshape(3,4))
print(arr.reshape(4,3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [2]:
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

7. Indexing

In [ ]:
#1D
arr=np.array((10,20,30,40))

print(arr[0])
print(arr[-1])

10
40


In [11]:
#2D
arr=np.array(([1,2,3],[4,5,6]))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
print(arr[0,1])
print(arr[1,2])

2
6


8. Slicing

In [13]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
print(arr[2:7])
print(arr[:5])
print(arr[5:])

[2 3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]


9. Mathematical Operations

In [15]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


10. Aggregate Functions

In [16]:
import numpy as np

In [17]:
arr = np.array([10,20,30,40])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.var(arr))

100
25.0
40
10
11.180339887498949
125.0


11. Axis Operations

In [19]:
arr=np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.sum(axis=0))
print(arr.sum(axis=1))

[5 7 9]
[ 6 15]
